// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// ConversationMessage is the predicate function for conversationmessage builders.
type ConversationMessage func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
