// Code generated by ent, DO NOT EDIT.

package conversationmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldActor, v))
}

// ActorType applies equality check predicate on the "actor_type" field. It's identical to ActorTypeEQ.
func ActorType(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldActorType, v))
}

// MessageType applies equality check predicate on the "message_type" field. It's identical to MessageTypeEQ.
func MessageType(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldMessageType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldConversationID, vs...))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldActor, v))
}

// ActorTypeEQ applies the EQ predicate on the "actor_type" field.
func ActorTypeEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldActorType, v))
}

// ActorTypeNEQ applies the NEQ predicate on the "actor_type" field.
func ActorTypeNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldActorType, v))
}

// ActorTypeIn applies the In predicate on the "actor_type" field.
func ActorTypeIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldActorType, vs...))
}

// ActorTypeNotIn applies the NotIn predicate on the "actor_type" field.
func ActorTypeNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldActorType, vs...))
}

// ActorTypeGT applies the GT predicate on the "actor_type" field.
func ActorTypeGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldActorType, v))
}

// ActorTypeGTE applies the GTE predicate on the "actor_type" field.
func ActorTypeGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldActorType, v))
}

// ActorTypeLT applies the LT predicate on the "actor_type" field.
func ActorTypeLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldActorType, v))
}

// ActorTypeLTE applies the LTE predicate on the "actor_type" field.
func ActorTypeLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldActorType, v))
}

// ActorTypeContains applies the Contains predicate on the "actor_type" field.
func ActorTypeContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldActorType, v))
}

// ActorTypeHasPrefix applies the HasPrefix predicate on the "actor_type" field.
func ActorTypeHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldActorType, v))
}

// ActorTypeHasSuffix applies the HasSuffix predicate on the "actor_type" field.
func ActorTypeHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldActorType, v))
}

// ActorTypeEqualFold applies the EqualFold predicate on the "actor_type" field.
func ActorTypeEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldActorType, v))
}

// ActorTypeContainsFold applies the ContainsFold predicate on the "actor_type" field.
func ActorTypeContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldActorType, v))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldMessageType, vs...))
}

// MessageTypeGT applies the GT predicate on the "message_type" field.
func MessageTypeGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldMessageType, v))
}

// MessageTypeGTE applies the GTE predicate on the "message_type" field.
func MessageTypeGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldMessageType, v))
}

// MessageTypeLT applies the LT predicate on the "message_type" field.
func MessageTypeLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldMessageType, v))
}

// MessageTypeLTE applies the LTE predicate on the "message_type" field.
func MessageTypeLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldMessageType, v))
}

// MessageTypeContains applies the Contains predicate on the "message_type" field.
func MessageTypeContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldMessageType, v))
}

// MessageTypeHasPrefix applies the HasPrefix predicate on the "message_type" field.
func MessageTypeHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldMessageType, v))
}

// MessageTypeHasSuffix applies the HasSuffix predicate on the "message_type" field.
func MessageTypeHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldMessageType, v))
}

// MessageTypeEqualFold applies the EqualFold predicate on the "message_type" field.
func MessageTypeEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldMessageType, v))
}

// MessageTypeContainsFold applies the ContainsFold predicate on the "message_type" field.
func MessageTypeContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldMessageType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasConversation applies the HasEdge predicate on the "conversation" edge.
func HasConversation() predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConversationWith applies the HasEdge predicate on the "conversation" edge with a given conditions (other predicates).
func HasConversationWith(preds ...predicate.Conversation) predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := newConversationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.NotPredicates(p))
}
