// Code generated by ent, DO NOT EDIT.

package conversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the conversation type in the database.
	Label = "conversation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTicketNo holds the string denoting the ticket_no field in the database.
	FieldTicketNo = "ticket_no"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldPreview holds the string denoting the preview field in the database.
	FieldPreview = "preview"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldQueue holds the string denoting the queue field in the database.
	FieldQueue = "queue"
	// FieldAssignee holds the string denoting the assignee field in the database.
	FieldAssignee = "assignee"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldUnread holds the string denoting the unread field in the database.
	FieldUnread = "unread"
	// FieldSLA holds the string denoting the sla field in the database.
	FieldSLA = "sla"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"
	// FieldCustomerCompany holds the string denoting the customer_company field in the database.
	FieldCustomerCompany = "customer_company"
	// FieldCustomerContact holds the string denoting the customer_contact field in the database.
	FieldCustomerContact = "customer_contact"
	// FieldCustomerTags holds the string denoting the customer_tags field in the database.
	FieldCustomerTags = "customer_tags"
	// FieldCustomerPresence holds the string denoting the customer_presence field in the database.
	FieldCustomerPresence = "customer_presence"
	// FieldCustomerTier holds the string denoting the customer_tier field in the database.
	FieldCustomerTier = "customer_tier"
	// FieldLastOrder holds the string denoting the last_order field in the database.
	FieldLastOrder = "last_order"
	// FieldOpenTickets holds the string denoting the open_tickets field in the database.
	FieldOpenTickets = "open_tickets"
	// FieldSatisfaction holds the string denoting the satisfaction field in the database.
	FieldSatisfaction = "satisfaction"
	// FieldLastActiveAt holds the string denoting the last_active_at field in the database.
	FieldLastActiveAt = "last_active_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the conversation in the database.
	Table = "conversations"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "conversation_messages"
	// MessagesInverseTable is the table name for the ConversationMessage entity.
	// It exists in this package in order to avoid circular dependency with the "conversationmessage" package.
	MessagesInverseTable = "conversation_messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "conversation_id"
)

// Columns holds all SQL columns for conversation fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTicketNo,
	FieldSubject,
	FieldPreview,
	FieldChannel,
	FieldQueue,
	FieldAssignee,
	FieldStatus,
	FieldPriority,
	FieldUnread,
	FieldSLA,
	FieldCustomerName,
	FieldCustomerCompany,
	FieldCustomerContact,
	FieldCustomerTags,
	FieldCustomerPresence,
	FieldCustomerTier,
	FieldLastOrder,
	FieldOpenTickets,
	FieldSatisfaction,
	FieldLastActiveAt,
	FieldClosedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TicketNoValidator is a validator for the "ticket_no" field. It is called by the builders before save.
	TicketNoValidator func(string) error
	// SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	SubjectValidator func(string) error
	// DefaultPreview holds the default value on creation for the "preview" field.
	DefaultPreview string
	// DefaultChannel holds the default value on creation for the "channel" field.
	DefaultChannel string
	// DefaultQueue holds the default value on creation for the "queue" field.
	DefaultQueue string
	// DefaultAssignee holds the default value on creation for the "assignee" field.
	DefaultAssignee string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority string
	// DefaultUnread holds the default value on creation for the "unread" field.
	DefaultUnread int
	// DefaultSLA holds the default value on creation for the "sla" field.
	DefaultSLA string
	// CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	CustomerNameValidator func(string) error
	// DefaultCustomerCompany holds the default value on creation for the "customer_company" field.
	DefaultCustomerCompany string
	// DefaultCustomerContact holds the default value on creation for the "customer_contact" field.
	DefaultCustomerContact string
	// DefaultCustomerTags holds the default value on creation for the "customer_tags" field.
	DefaultCustomerTags []string
	// DefaultCustomerPresence holds the default value on creation for the "customer_presence" field.
	DefaultCustomerPresence string
	// DefaultCustomerTier holds the default value on creation for the "customer_tier" field.
	DefaultCustomerTier string
	// DefaultLastOrder holds the default value on creation for the "last_order" field.
	DefaultLastOrder string
	// DefaultOpenTickets holds the default value on creation for the "open_tickets" field.
	DefaultOpenTickets int
	// DefaultSatisfaction holds the default value on creation for the "satisfaction" field.
	DefaultSatisfaction string
	// DefaultLastActiveAt holds the default value on creation for the "last_active_at" field.
	DefaultLastActiveAt func() time.Time
)

// OrderOption defines the ordering options for the Conversation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTicketNo orders the results by the ticket_no field.
func ByTicketNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketNo, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByPreview orders the results by the preview field.
func ByPreview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreview, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByQueue orders the results by the queue field.
func ByQueue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueue, opts...).ToFunc()
}

// ByAssignee orders the results by the assignee field.
func ByAssignee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignee, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByUnread orders the results by the unread field.
func ByUnread(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnread, opts...).ToFunc()
}

// BySLA orders the results by the sla field.
func BySLA(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSLA, opts...).ToFunc()
}

// ByCustomerName orders the results by the customer_name field.
func ByCustomerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerName, opts...).ToFunc()
}

// ByCustomerCompany orders the results by the customer_company field.
func ByCustomerCompany(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerCompany, opts...).ToFunc()
}

// ByCustomerContact orders the results by the customer_contact field.
func ByCustomerContact(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerContact, opts...).ToFunc()
}

// ByCustomerPresence orders the results by the customer_presence field.
func ByCustomerPresence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerPresence, opts...).ToFunc()
}

// ByCustomerTier orders the results by the customer_tier field.
func ByCustomerTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerTier, opts...).ToFunc()
}

// ByLastOrder orders the results by the last_order field.
func ByLastOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastOrder, opts...).ToFunc()
}

// ByOpenTickets orders the results by the open_tickets field.
func ByOpenTickets(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenTickets, opts...).ToFunc()
}

// BySatisfaction orders the results by the satisfaction field.
func BySatisfaction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSatisfaction, opts...).ToFunc()
}

// ByLastActiveAt orders the results by the last_active_at field.
func ByLastActiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActiveAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
