// Code generated by ent, DO NOT EDIT.

package conversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// TicketNo applies equality check predicate on the "ticket_no" field. It's identical to TicketNoEQ.
func TicketNo(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldTicketNo, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSubject, v))
}

// Preview applies equality check predicate on the "preview" field. It's identical to PreviewEQ.
func Preview(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPreview, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldChannel, v))
}

// Queue applies equality check predicate on the "queue" field. It's identical to QueueEQ.
func Queue(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldQueue, v))
}

// Assignee applies equality check predicate on the "assignee" field. It's identical to AssigneeEQ.
func Assignee(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAssignee, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldStatus, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPriority, v))
}

// Unread applies equality check predicate on the "unread" field. It's identical to UnreadEQ.
func Unread(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUnread, v))
}

// SLA applies equality check predicate on the "sla" field. It's identical to SLAEQ.
func SLA(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSLA, v))
}

// CustomerName applies equality check predicate on the "customer_name" field. It's identical to CustomerNameEQ.
func CustomerName(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerCompany applies equality check predicate on the "customer_company" field. It's identical to CustomerCompanyEQ.
func CustomerCompany(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerCompany, v))
}

// CustomerContact applies equality check predicate on the "customer_contact" field. It's identical to CustomerContactEQ.
func CustomerContact(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerContact, v))
}

// CustomerPresence applies equality check predicate on the "customer_presence" field. It's identical to CustomerPresenceEQ.
func CustomerPresence(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerPresence, v))
}

// CustomerTier applies equality check predicate on the "customer_tier" field. It's identical to CustomerTierEQ.
func CustomerTier(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerTier, v))
}

// LastOrder applies equality check predicate on the "last_order" field. It's identical to LastOrderEQ.
func LastOrder(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastOrder, v))
}

// OpenTickets applies equality check predicate on the "open_tickets" field. It's identical to OpenTicketsEQ.
func OpenTickets(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldOpenTickets, v))
}

// Satisfaction applies equality check predicate on the "satisfaction" field. It's identical to SatisfactionEQ.
func Satisfaction(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSatisfaction, v))
}

// LastActiveAt applies equality check predicate on the "last_active_at" field. It's identical to LastActiveAtEQ.
func LastActiveAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastActiveAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldUpdatedAt, v))
}

// TicketNoEQ applies the EQ predicate on the "ticket_no" field.
func TicketNoEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldTicketNo, v))
}

// TicketNoNEQ applies the NEQ predicate on the "ticket_no" field.
func TicketNoNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldTicketNo, v))
}

// TicketNoIn applies the In predicate on the "ticket_no" field.
func TicketNoIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldTicketNo, vs...))
}

// TicketNoNotIn applies the NotIn predicate on the "ticket_no" field.
func TicketNoNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldTicketNo, vs...))
}

// TicketNoGT applies the GT predicate on the "ticket_no" field.
func TicketNoGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldTicketNo, v))
}

// TicketNoGTE applies the GTE predicate on the "ticket_no" field.
func TicketNoGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldTicketNo, v))
}

// TicketNoLT applies the LT predicate on the "ticket_no" field.
func TicketNoLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldTicketNo, v))
}

// TicketNoLTE applies the LTE predicate on the "ticket_no" field.
func TicketNoLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldTicketNo, v))
}

// TicketNoContains applies the Contains predicate on the "ticket_no" field.
func TicketNoContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldTicketNo, v))
}

// TicketNoHasPrefix applies the HasPrefix predicate on the "ticket_no" field.
func TicketNoHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldTicketNo, v))
}

// TicketNoHasSuffix applies the HasSuffix predicate on the "ticket_no" field.
func TicketNoHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldTicketNo, v))
}

// TicketNoEqualFold applies the EqualFold predicate on the "ticket_no" field.
func TicketNoEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldTicketNo, v))
}

// TicketNoContainsFold applies the ContainsFold predicate on the "ticket_no" field.
func TicketNoContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldTicketNo, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSubject, v))
}

// PreviewEQ applies the EQ predicate on the "preview" field.
func PreviewEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPreview, v))
}

// PreviewNEQ applies the NEQ predicate on the "preview" field.
func PreviewNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldPreview, v))
}

// PreviewIn applies the In predicate on the "preview" field.
func PreviewIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldPreview, vs...))
}

// PreviewNotIn applies the NotIn predicate on the "preview" field.
func PreviewNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldPreview, vs...))
}

// PreviewGT applies the GT predicate on the "preview" field.
func PreviewGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldPreview, v))
}

// PreviewGTE applies the GTE predicate on the "preview" field.
func PreviewGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldPreview, v))
}

// PreviewLT applies the LT predicate on the "preview" field.
func PreviewLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldPreview, v))
}

// PreviewLTE applies the LTE predicate on the "preview" field.
func PreviewLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldPreview, v))
}

// PreviewContains applies the Contains predicate on the "preview" field.
func PreviewContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldPreview, v))
}

// PreviewHasPrefix applies the HasPrefix predicate on the "preview" field.
func PreviewHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldPreview, v))
}

// PreviewHasSuffix applies the HasSuffix predicate on the "preview" field.
func PreviewHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldPreview, v))
}

// PreviewEqualFold applies the EqualFold predicate on the "preview" field.
func PreviewEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldPreview, v))
}

// PreviewContainsFold applies the ContainsFold predicate on the "preview" field.
func PreviewContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldPreview, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldChannel, v))
}

// QueueEQ applies the EQ predicate on the "queue" field.
func QueueEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldQueue, v))
}

// QueueNEQ applies the NEQ predicate on the "queue" field.
func QueueNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldQueue, v))
}

// QueueIn applies the In predicate on the "queue" field.
func QueueIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldQueue, vs...))
}

// QueueNotIn applies the NotIn predicate on the "queue" field.
func QueueNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldQueue, vs...))
}

// QueueGT applies the GT predicate on the "queue" field.
func QueueGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldQueue, v))
}

// QueueGTE applies the GTE predicate on the "queue" field.
func QueueGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldQueue, v))
}

// QueueLT applies the LT predicate on the "queue" field.
func QueueLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldQueue, v))
}

// QueueLTE applies the LTE predicate on the "queue" field.
func QueueLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldQueue, v))
}

// QueueContains applies the Contains predicate on the "queue" field.
func QueueContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldQueue, v))
}

// QueueHasPrefix applies the HasPrefix predicate on the "queue" field.
func QueueHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldQueue, v))
}

// QueueHasSuffix applies the HasSuffix predicate on the "queue" field.
func QueueHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldQueue, v))
}

// QueueEqualFold applies the EqualFold predicate on the "queue" field.
func QueueEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldQueue, v))
}

// QueueContainsFold applies the ContainsFold predicate on the "queue" field.
func QueueContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldQueue, v))
}

// AssigneeEQ applies the EQ predicate on the "assignee" field.
func AssigneeEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAssignee, v))
}

// AssigneeNEQ applies the NEQ predicate on the "assignee" field.
func AssigneeNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldAssignee, v))
}

// AssigneeIn applies the In predicate on the "assignee" field.
func AssigneeIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldAssignee, vs...))
}

// AssigneeNotIn applies the NotIn predicate on the "assignee" field.
func AssigneeNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldAssignee, vs...))
}

// AssigneeGT applies the GT predicate on the "assignee" field.
func AssigneeGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldAssignee, v))
}

// AssigneeGTE applies the GTE predicate on the "assignee" field.
func AssigneeGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldAssignee, v))
}

// AssigneeLT applies the LT predicate on the "assignee" field.
func AssigneeLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldAssignee, v))
}

// AssigneeLTE applies the LTE predicate on the "assignee" field.
func AssigneeLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldAssignee, v))
}

// AssigneeContains applies the Contains predicate on the "assignee" field.
func AssigneeContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldAssignee, v))
}

// AssigneeHasPrefix applies the HasPrefix predicate on the "assignee" field.
func AssigneeHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldAssignee, v))
}

// AssigneeHasSuffix applies the HasSuffix predicate on the "assignee" field.
func AssigneeHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldAssignee, v))
}

// AssigneeEqualFold applies the EqualFold predicate on the "assignee" field.
func AssigneeEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldAssignee, v))
}

// AssigneeContainsFold applies the ContainsFold predicate on the "assignee" field.
func AssigneeContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldAssignee, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldStatus, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldPriority, v))
}

// UnreadEQ applies the EQ predicate on the "unread" field.
func UnreadEQ(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUnread, v))
}

// UnreadNEQ applies the NEQ predicate on the "unread" field.
func UnreadNEQ(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUnread, v))
}

// UnreadIn applies the In predicate on the "unread" field.
func UnreadIn(vs ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUnread, vs...))
}

// UnreadNotIn applies the NotIn predicate on the "unread" field.
func UnreadNotIn(vs ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUnread, vs...))
}

// UnreadGT applies the GT predicate on the "unread" field.
func UnreadGT(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldUnread, v))
}

// UnreadGTE applies the GTE predicate on the "unread" field.
func UnreadGTE(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldUnread, v))
}

// UnreadLT applies the LT predicate on the "unread" field.
func UnreadLT(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldUnread, v))
}

// UnreadLTE applies the LTE predicate on the "unread" field.
func UnreadLTE(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldUnread, v))
}

// SLAEQ applies the EQ predicate on the "sla" field.
func SLAEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSLA, v))
}

// SLANEQ applies the NEQ predicate on the "sla" field.
func SLANEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSLA, v))
}

// SLAIn applies the In predicate on the "sla" field.
func SLAIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSLA, vs...))
}

// SLANotIn applies the NotIn predicate on the "sla" field.
func SLANotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSLA, vs...))
}

// SLAGT applies the GT predicate on the "sla" field.
func SLAGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSLA, v))
}

// SLAGTE applies the GTE predicate on the "sla" field.
func SLAGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSLA, v))
}

// SLALT applies the LT predicate on the "sla" field.
func SLALT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSLA, v))
}

// SLALTE applies the LTE predicate on the "sla" field.
func SLALTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSLA, v))
}

// SLAContains applies the Contains predicate on the "sla" field.
func SLAContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSLA, v))
}

// SLAHasPrefix applies the HasPrefix predicate on the "sla" field.
func SLAHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSLA, v))
}

// SLAHasSuffix applies the HasSuffix predicate on the "sla" field.
func SLAHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSLA, v))
}

// SLAEqualFold applies the EqualFold predicate on the "sla" field.
func SLAEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSLA, v))
}

// SLAContainsFold applies the ContainsFold predicate on the "sla" field.
func SLAContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSLA, v))
}

// CustomerNameEQ applies the EQ predicate on the "customer_name" field.
func CustomerNameEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerNameNEQ applies the NEQ predicate on the "customer_name" field.
func CustomerNameNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCustomerName, v))
}

// CustomerNameIn applies the In predicate on the "customer_name" field.
func CustomerNameIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCustomerName, vs...))
}

// CustomerNameNotIn applies the NotIn predicate on the "customer_name" field.
func CustomerNameNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCustomerName, vs...))
}

// CustomerNameGT applies the GT predicate on the "customer_name" field.
func CustomerNameGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCustomerName, v))
}

// CustomerNameGTE applies the GTE predicate on the "customer_name" field.
func CustomerNameGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCustomerName, v))
}

// CustomerNameLT applies the LT predicate on the "customer_name" field.
func CustomerNameLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCustomerName, v))
}

// CustomerNameLTE applies the LTE predicate on the "customer_name" field.
func CustomerNameLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCustomerName, v))
}

// CustomerNameContains applies the Contains predicate on the "customer_name" field.
func CustomerNameContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldCustomerName, v))
}

// CustomerNameHasPrefix applies the HasPrefix predicate on the "customer_name" field.
func CustomerNameHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldCustomerName, v))
}

// CustomerNameHasSuffix applies the HasSuffix predicate on the "customer_name" field.
func CustomerNameHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldCustomerName, v))
}

// CustomerNameEqualFold applies the EqualFold predicate on the "customer_name" field.
func CustomerNameEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldCustomerName, v))
}

// CustomerNameContainsFold applies the ContainsFold predicate on the "customer_name" field.
func CustomerNameContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldCustomerName, v))
}

// CustomerCompanyEQ applies the EQ predicate on the "customer_company" field.
func CustomerCompanyEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerCompany, v))
}

// CustomerCompanyNEQ applies the NEQ predicate on the "customer_company" field.
func CustomerCompanyNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCustomerCompany, v))
}

// CustomerCompanyIn applies the In predicate on the "customer_company" field.
func CustomerCompanyIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCustomerCompany, vs...))
}

// CustomerCompanyNotIn applies the NotIn predicate on the "customer_company" field.
func CustomerCompanyNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCustomerCompany, vs...))
}

// CustomerCompanyGT applies the GT predicate on the "customer_company" field.
func CustomerCompanyGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCustomerCompany, v))
}

// CustomerCompanyGTE applies the GTE predicate on the "customer_company" field.
func CustomerCompanyGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCustomerCompany, v))
}

// CustomerCompanyLT applies the LT predicate on the "customer_company" field.
func CustomerCompanyLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCustomerCompany, v))
}

// CustomerCompanyLTE applies the LTE predicate on the "customer_company" field.
func CustomerCompanyLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCustomerCompany, v))
}

// CustomerCompanyContains applies the Contains predicate on the "customer_company" field.
func CustomerCompanyContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldCustomerCompany, v))
}

// CustomerCompanyHasPrefix applies the HasPrefix predicate on the "customer_company" field.
func CustomerCompanyHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldCustomerCompany, v))
}

// CustomerCompanyHasSuffix applies the HasSuffix predicate on the "customer_company" field.
func CustomerCompanyHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldCustomerCompany, v))
}

// CustomerCompanyEqualFold applies the EqualFold predicate on the "customer_company" field.
func CustomerCompanyEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldCustomerCompany, v))
}

// CustomerCompanyContainsFold applies the ContainsFold predicate on the "customer_company" field.
func CustomerCompanyContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldCustomerCompany, v))
}

// CustomerContactEQ applies the EQ predicate on the "customer_contact" field.
func CustomerContactEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerContact, v))
}

// CustomerContactNEQ applies the NEQ predicate on the "customer_contact" field.
func CustomerContactNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCustomerContact, v))
}

// CustomerContactIn applies the In predicate on the "customer_contact" field.
func CustomerContactIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCustomerContact, vs...))
}

// CustomerContactNotIn applies the NotIn predicate on the "customer_contact" field.
func CustomerContactNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCustomerContact, vs...))
}

// CustomerContactGT applies the GT predicate on the "customer_contact" field.
func CustomerContactGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCustomerContact, v))
}

// CustomerContactGTE applies the GTE predicate on the "customer_contact" field.
func CustomerContactGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCustomerContact, v))
}

// CustomerContactLT applies the LT predicate on the "customer_contact" field.
func CustomerContactLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCustomerContact, v))
}

// CustomerContactLTE applies the LTE predicate on the "customer_contact" field.
func CustomerContactLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCustomerContact, v))
}

// CustomerContactContains applies the Contains predicate on the "customer_contact" field.
func CustomerContactContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldCustomerContact, v))
}

// CustomerContactHasPrefix applies the HasPrefix predicate on the "customer_contact" field.
func CustomerContactHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldCustomerContact, v))
}

// CustomerContactHasSuffix applies the HasSuffix predicate on the "customer_contact" field.
func CustomerContactHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldCustomerContact, v))
}

// CustomerContactEqualFold applies the EqualFold predicate on the "customer_contact" field.
func CustomerContactEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldCustomerContact, v))
}

// CustomerContactContainsFold applies the ContainsFold predicate on the "customer_contact" field.
func CustomerContactContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldCustomerContact, v))
}

// CustomerPresenceEQ applies the EQ predicate on the "customer_presence" field.
func CustomerPresenceEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerPresence, v))
}

// CustomerPresenceNEQ applies the NEQ predicate on the "customer_presence" field.
func CustomerPresenceNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCustomerPresence, v))
}

// CustomerPresenceIn applies the In predicate on the "customer_presence" field.
func CustomerPresenceIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCustomerPresence, vs...))
}

// CustomerPresenceNotIn applies the NotIn predicate on the "customer_presence" field.
func CustomerPresenceNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCustomerPresence, vs...))
}

// CustomerPresenceGT applies the GT predicate on the "customer_presence" field.
func CustomerPresenceGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCustomerPresence, v))
}

// CustomerPresenceGTE applies the GTE predicate on the "customer_presence" field.
func CustomerPresenceGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCustomerPresence, v))
}

// CustomerPresenceLT applies the LT predicate on the "customer_presence" field.
func CustomerPresenceLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCustomerPresence, v))
}

// CustomerPresenceLTE applies the LTE predicate on the "customer_presence" field.
func CustomerPresenceLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCustomerPresence, v))
}

// CustomerPresenceContains applies the Contains predicate on the "customer_presence" field.
func CustomerPresenceContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldCustomerPresence, v))
}

// CustomerPresenceHasPrefix applies the HasPrefix predicate on the "customer_presence" field.
func CustomerPresenceHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldCustomerPresence, v))
}

// CustomerPresenceHasSuffix applies the HasSuffix predicate on the "customer_presence" field.
func CustomerPresenceHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldCustomerPresence, v))
}

// CustomerPresenceEqualFold applies the EqualFold predicate on the "customer_presence" field.
func CustomerPresenceEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldCustomerPresence, v))
}

// CustomerPresenceContainsFold applies the ContainsFold predicate on the "customer_presence" field.
func CustomerPresenceContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldCustomerPresence, v))
}

// CustomerTierEQ applies the EQ predicate on the "customer_tier" field.
func CustomerTierEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCustomerTier, v))
}

// CustomerTierNEQ applies the NEQ predicate on the "customer_tier" field.
func CustomerTierNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCustomerTier, v))
}

// CustomerTierIn applies the In predicate on the "customer_tier" field.
func CustomerTierIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCustomerTier, vs...))
}

// CustomerTierNotIn applies the NotIn predicate on the "customer_tier" field.
func CustomerTierNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCustomerTier, vs...))
}

// CustomerTierGT applies the GT predicate on the "customer_tier" field.
func CustomerTierGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCustomerTier, v))
}

// CustomerTierGTE applies the GTE predicate on the "customer_tier" field.
func CustomerTierGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCustomerTier, v))
}

// CustomerTierLT applies the LT predicate on the "customer_tier" field.
func CustomerTierLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCustomerTier, v))
}

// CustomerTierLTE applies the LTE predicate on the "customer_tier" field.
func CustomerTierLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCustomerTier, v))
}

// CustomerTierContains applies the Contains predicate on the "customer_tier" field.
func CustomerTierContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldCustomerTier, v))
}

// CustomerTierHasPrefix applies the HasPrefix predicate on the "customer_tier" field.
func CustomerTierHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldCustomerTier, v))
}

// CustomerTierHasSuffix applies the HasSuffix predicate on the "customer_tier" field.
func CustomerTierHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldCustomerTier, v))
}

// CustomerTierEqualFold applies the EqualFold predicate on the "customer_tier" field.
func CustomerTierEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldCustomerTier, v))
}

// CustomerTierContainsFold applies the ContainsFold predicate on the "customer_tier" field.
func CustomerTierContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldCustomerTier, v))
}

// LastOrderEQ applies the EQ predicate on the "last_order" field.
func LastOrderEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastOrder, v))
}

// LastOrderNEQ applies the NEQ predicate on the "last_order" field.
func LastOrderNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastOrder, v))
}

// LastOrderIn applies the In predicate on the "last_order" field.
func LastOrderIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastOrder, vs...))
}

// LastOrderNotIn applies the NotIn predicate on the "last_order" field.
func LastOrderNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastOrder, vs...))
}

// LastOrderGT applies the GT predicate on the "last_order" field.
func LastOrderGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastOrder, v))
}

// LastOrderGTE applies the GTE predicate on the "last_order" field.
func LastOrderGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastOrder, v))
}

// LastOrderLT applies the LT predicate on the "last_order" field.
func LastOrderLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastOrder, v))
}

// LastOrderLTE applies the LTE predicate on the "last_order" field.
func LastOrderLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastOrder, v))
}

// LastOrderContains applies the Contains predicate on the "last_order" field.
func LastOrderContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldLastOrder, v))
}

// LastOrderHasPrefix applies the HasPrefix predicate on the "last_order" field.
func LastOrderHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldLastOrder, v))
}

// LastOrderHasSuffix applies the HasSuffix predicate on the "last_order" field.
func LastOrderHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldLastOrder, v))
}

// LastOrderEqualFold applies the EqualFold predicate on the "last_order" field.
func LastOrderEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldLastOrder, v))
}

// LastOrderContainsFold applies the ContainsFold predicate on the "last_order" field.
func LastOrderContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldLastOrder, v))
}

// OpenTicketsEQ applies the EQ predicate on the "open_tickets" field.
func OpenTicketsEQ(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldOpenTickets, v))
}

// OpenTicketsNEQ applies the NEQ predicate on the "open_tickets" field.
func OpenTicketsNEQ(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldOpenTickets, v))
}

// OpenTicketsIn applies the In predicate on the "open_tickets" field.
func OpenTicketsIn(vs ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldOpenTickets, vs...))
}

// OpenTicketsNotIn applies the NotIn predicate on the "open_tickets" field.
func OpenTicketsNotIn(vs ...int) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldOpenTickets, vs...))
}

// OpenTicketsGT applies the GT predicate on the "open_tickets" field.
func OpenTicketsGT(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldOpenTickets, v))
}

// OpenTicketsGTE applies the GTE predicate on the "open_tickets" field.
func OpenTicketsGTE(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldOpenTickets, v))
}

// OpenTicketsLT applies the LT predicate on the "open_tickets" field.
func OpenTicketsLT(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldOpenTickets, v))
}

// OpenTicketsLTE applies the LTE predicate on the "open_tickets" field.
func OpenTicketsLTE(v int) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldOpenTickets, v))
}

// SatisfactionEQ applies the EQ predicate on the "satisfaction" field.
func SatisfactionEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSatisfaction, v))
}

// SatisfactionNEQ applies the NEQ predicate on the "satisfaction" field.
func SatisfactionNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSatisfaction, v))
}

// SatisfactionIn applies the In predicate on the "satisfaction" field.
func SatisfactionIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSatisfaction, vs...))
}

// SatisfactionNotIn applies the NotIn predicate on the "satisfaction" field.
func SatisfactionNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSatisfaction, vs...))
}

// SatisfactionGT applies the GT predicate on the "satisfaction" field.
func SatisfactionGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSatisfaction, v))
}

// SatisfactionGTE applies the GTE predicate on the "satisfaction" field.
func SatisfactionGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSatisfaction, v))
}

// SatisfactionLT applies the LT predicate on the "satisfaction" field.
func SatisfactionLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSatisfaction, v))
}

// SatisfactionLTE applies the LTE predicate on the "satisfaction" field.
func SatisfactionLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSatisfaction, v))
}

// SatisfactionContains applies the Contains predicate on the "satisfaction" field.
func SatisfactionContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSatisfaction, v))
}

// SatisfactionHasPrefix applies the HasPrefix predicate on the "satisfaction" field.
func SatisfactionHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSatisfaction, v))
}

// SatisfactionHasSuffix applies the HasSuffix predicate on the "satisfaction" field.
func SatisfactionHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSatisfaction, v))
}

// SatisfactionEqualFold applies the EqualFold predicate on the "satisfaction" field.
func SatisfactionEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSatisfaction, v))
}

// SatisfactionContainsFold applies the ContainsFold predicate on the "satisfaction" field.
func SatisfactionContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSatisfaction, v))
}

// LastActiveAtEQ applies the EQ predicate on the "last_active_at" field.
func LastActiveAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastActiveAt, v))
}

// LastActiveAtNEQ applies the NEQ predicate on the "last_active_at" field.
func LastActiveAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastActiveAt, v))
}

// LastActiveAtIn applies the In predicate on the "last_active_at" field.
func LastActiveAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastActiveAt, vs...))
}

// LastActiveAtNotIn applies the NotIn predicate on the "last_active_at" field.
func LastActiveAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastActiveAt, vs...))
}

// LastActiveAtGT applies the GT predicate on the "last_active_at" field.
func LastActiveAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastActiveAt, v))
}

// LastActiveAtGTE applies the GTE predicate on the "last_active_at" field.
func LastActiveAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastActiveAt, v))
}

// LastActiveAtLT applies the LT predicate on the "last_active_at" field.
func LastActiveAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastActiveAt, v))
}

// LastActiveAtLTE applies the LTE predicate on the "last_active_at" field.
func LastActiveAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastActiveAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldClosedAt))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.ConversationMessage) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.NotPredicates(p))
}
