// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/auditlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *AuditLogUpdate) SetUsername(v string) *AuditLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUsername(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetModule sets the "module" field.
func (_u *AuditLogUpdate) SetModule(v string) *AuditLogUpdate {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableModule(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AuditLogUpdate) SetMethod(v string) *AuditLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableMethod(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AuditLogUpdate) SetPath(v string) *AuditLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillablePath(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AuditLogUpdate) SetStatusCode(v int) *AuditLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableStatusCode(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AuditLogUpdate) AddStatusCode(v int) *AuditLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdate) SetIP(v string) *AuditLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIP(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditLogUpdate) SetDetail(v string) *AuditLogUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableDetail(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdate) SetCreatedAt(v time.Time) *AuditLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableCreatedAt(v *time.Time) *AuditLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(auditlog.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(auditlog.FieldModule, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetUsername sets the "username" field.
func (_u *AuditLogUpdateOne) SetUsername(v string) *AuditLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUsername(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetModule sets the "module" field.
func (_u *AuditLogUpdateOne) SetModule(v string) *AuditLogUpdateOne {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableModule(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AuditLogUpdateOne) SetMethod(v string) *AuditLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableMethod(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *AuditLogUpdateOne) SetPath(v string) *AuditLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillablePath(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *AuditLogUpdateOne) SetStatusCode(v int) *AuditLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableStatusCode(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *AuditLogUpdateOne) AddStatusCode(v int) *AuditLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetIP sets the "ip" field.
func (_u *AuditLogUpdateOne) SetIP(v string) *AuditLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIP(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditLogUpdateOne) SetDetail(v string) *AuditLogUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableDetail(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdateOne) SetCreatedAt(v time.Time) *AuditLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(auditlog.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(auditlog.FieldModule, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
