// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/auditlog"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *AuditLogCreate) SetUsername(v string) *AuditLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUsername(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetModule sets the "module" field.
func (_c *AuditLogCreate) SetModule(v string) *AuditLogCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableModule(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetModule(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditLogCreate) SetAction(v string) *AuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableAction(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AuditLogCreate) SetMethod(v string) *AuditLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableMethod(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AuditLogCreate) SetPath(v string) *AuditLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillablePath(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *AuditLogCreate) SetStatusCode(v int) *AuditLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableStatusCode(v *int) *AuditLogCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *AuditLogCreate) SetIP(v string) *AuditLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableIP(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *AuditLogCreate) SetDetail(v string) *AuditLogCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableDetail(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditLogCreate) SetCreatedAt(v time.Time) *AuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableCreatedAt(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() {
	if _, ok := _c.mutation.Username(); !ok {
		v := auditlog.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Module(); !ok {
		v := auditlog.DefaultModule
		_c.mutation.SetModule(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := auditlog.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := auditlog.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := auditlog.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := auditlog.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.IP(); !ok {
		v := auditlog.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.Detail(); !ok {
		v := auditlog.DefaultDetail
		_c.mutation.SetDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AuditLog.username"`)}
	}
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "AuditLog.module"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditLog.action"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "AuditLog.method"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AuditLog.path"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "AuditLog.status_code"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "AuditLog.ip"`)}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "AuditLog.detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditLog.created_at"`)}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(auditlog.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(auditlog.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(auditlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(auditlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
