// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ConversationUpdate is the builder for updating Conversation entities.
type ConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdate) Where(ps ...predicate.Conversation) *ConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdate) SetUpdatedAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTicketNo sets the "ticket_no" field.
func (_u *ConversationUpdate) SetTicketNo(v string) *ConversationUpdate {
	_u.mutation.SetTicketNo(v)
	return _u
}

// SetNillableTicketNo sets the "ticket_no" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableTicketNo(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetTicketNo(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ConversationUpdate) SetSubject(v string) *ConversationUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSubject(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPreview sets the "preview" field.
func (_u *ConversationUpdate) SetPreview(v string) *ConversationUpdate {
	_u.mutation.SetPreview(v)
	return _u
}

// SetNillablePreview sets the "preview" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillablePreview(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetPreview(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *ConversationUpdate) SetChannel(v string) *ConversationUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableChannel(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetQueue sets the "queue" field.
func (_u *ConversationUpdate) SetQueue(v string) *ConversationUpdate {
	_u.mutation.SetQueue(v)
	return _u
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableQueue(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetQueue(*v)
	}
	return _u
}

// SetAssignee sets the "assignee" field.
func (_u *ConversationUpdate) SetAssignee(v string) *ConversationUpdate {
	_u.mutation.SetAssignee(v)
	return _u
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableAssignee(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetAssignee(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdate) SetStatus(v string) *ConversationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableStatus(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ConversationUpdate) SetPriority(v string) *ConversationUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillablePriority(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetUnread sets the "unread" field.
func (_u *ConversationUpdate) SetUnread(v int) *ConversationUpdate {
	_u.mutation.ResetUnread()
	_u.mutation.SetUnread(v)
	return _u
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableUnread(v *int) *ConversationUpdate {
	if v != nil {
		_u.SetUnread(*v)
	}
	return _u
}

// AddUnread adds value to the "unread" field.
func (_u *ConversationUpdate) AddUnread(v int) *ConversationUpdate {
	_u.mutation.AddUnread(v)
	return _u
}

// SetSLA sets the "sla" field.
func (_u *ConversationUpdate) SetSLA(v string) *ConversationUpdate {
	_u.mutation.SetSLA(v)
	return _u
}

// SetNillableSLA sets the "sla" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSLA(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSLA(*v)
	}
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *ConversationUpdate) SetCustomerName(v string) *ConversationUpdate {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCustomerName(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// SetCustomerCompany sets the "customer_company" field.
func (_u *ConversationUpdate) SetCustomerCompany(v string) *ConversationUpdate {
	_u.mutation.SetCustomerCompany(v)
	return _u
}

// SetNillableCustomerCompany sets the "customer_company" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCustomerCompany(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCustomerCompany(*v)
	}
	return _u
}

// SetCustomerContact sets the "customer_contact" field.
func (_u *ConversationUpdate) SetCustomerContact(v string) *ConversationUpdate {
	_u.mutation.SetCustomerContact(v)
	return _u
}

// SetNillableCustomerContact sets the "customer_contact" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCustomerContact(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCustomerContact(*v)
	}
	return _u
}

// SetCustomerTags sets the "customer_tags" field.
func (_u *ConversationUpdate) SetCustomerTags(v []string) *ConversationUpdate {
	_u.mutation.SetCustomerTags(v)
	return _u
}

// AppendCustomerTags appends value to the "customer_tags" field.
func (_u *ConversationUpdate) AppendCustomerTags(v []string) *ConversationUpdate {
	_u.mutation.AppendCustomerTags(v)
	return _u
}

// SetCustomerPresence sets the "customer_presence" field.
func (_u *ConversationUpdate) SetCustomerPresence(v string) *ConversationUpdate {
	_u.mutation.SetCustomerPresence(v)
	return _u
}

// SetNillableCustomerPresence sets the "customer_presence" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCustomerPresence(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCustomerPresence(*v)
	}
	return _u
}

// SetCustomerTier sets the "customer_tier" field.
func (_u *ConversationUpdate) SetCustomerTier(v string) *ConversationUpdate {
	_u.mutation.SetCustomerTier(v)
	return _u
}

// SetNillableCustomerTier sets the "customer_tier" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableCustomerTier(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetCustomerTier(*v)
	}
	return _u
}

// SetLastOrder sets the "last_order" field.
func (_u *ConversationUpdate) SetLastOrder(v string) *ConversationUpdate {
	_u.mutation.SetLastOrder(v)
	return _u
}

// SetNillableLastOrder sets the "last_order" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastOrder(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetLastOrder(*v)
	}
	return _u
}

// SetOpenTickets sets the "open_tickets" field.
func (_u *ConversationUpdate) SetOpenTickets(v int) *ConversationUpdate {
	_u.mutation.ResetOpenTickets()
	_u.mutation.SetOpenTickets(v)
	return _u
}

// SetNillableOpenTickets sets the "open_tickets" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableOpenTickets(v *int) *ConversationUpdate {
	if v != nil {
		_u.SetOpenTickets(*v)
	}
	return _u
}

// AddOpenTickets adds value to the "open_tickets" field.
func (_u *ConversationUpdate) AddOpenTickets(v int) *ConversationUpdate {
	_u.mutation.AddOpenTickets(v)
	return _u
}

// SetSatisfaction sets the "satisfaction" field.
func (_u *ConversationUpdate) SetSatisfaction(v string) *ConversationUpdate {
	_u.mutation.SetSatisfaction(v)
	return _u
}

// SetNillableSatisfaction sets the "satisfaction" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSatisfaction(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSatisfaction(*v)
	}
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *ConversationUpdate) SetLastActiveAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastActiveAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *ConversationUpdate) SetClosedAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableClosedAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *ConversationUpdate) ClearClosedAt() *ConversationUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_u *ConversationUpdate) AddMessageIDs(ids ...int) *ConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdate) AddMessages(v ...*ConversationMessage) *ConversationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdate) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdate) ClearMessages() *ConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ConversationMessage entities by IDs.
func (_u *ConversationUpdate) RemoveMessageIDs(ids ...int) *ConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ConversationMessage entities.
func (_u *ConversationUpdate) RemoveMessages(v ...*ConversationMessage) *ConversationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdate) check() error {
	if v, ok := _u.mutation.TicketNo(); ok {
		if err := conversation.TicketNoValidator(v); err != nil {
			return &ValidationError{Name: "ticket_no", err: fmt.Errorf(`ent: validator failed for field "Conversation.ticket_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomerName(); ok {
		if err := conversation.CustomerNameValidator(v); err != nil {
			return &ValidationError{Name: "customer_name", err: fmt.Errorf(`ent: validator failed for field "Conversation.customer_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TicketNo(); ok {
		_spec.SetField(conversation.FieldTicketNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preview(); ok {
		_spec.SetField(conversation.FieldPreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(conversation.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Queue(); ok {
		_spec.SetField(conversation.FieldQueue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assignee(); ok {
		_spec.SetField(conversation.FieldAssignee, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unread(); ok {
		_spec.SetField(conversation.FieldUnread, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnread(); ok {
		_spec.AddField(conversation.FieldUnread, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SLA(); ok {
		_spec.SetField(conversation.FieldSLA, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(conversation.FieldCustomerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerCompany(); ok {
		_spec.SetField(conversation.FieldCustomerCompany, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerContact(); ok {
		_spec.SetField(conversation.FieldCustomerContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerTags(); ok {
		_spec.SetField(conversation.FieldCustomerTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCustomerTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversation.FieldCustomerTags, value)
		})
	}
	if value, ok := _u.mutation.CustomerPresence(); ok {
		_spec.SetField(conversation.FieldCustomerPresence, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerTier(); ok {
		_spec.SetField(conversation.FieldCustomerTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastOrder(); ok {
		_spec.SetField(conversation.FieldLastOrder, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenTickets(); ok {
		_spec.SetField(conversation.FieldOpenTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenTickets(); ok {
		_spec.AddField(conversation.FieldOpenTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Satisfaction(); ok {
		_spec.SetField(conversation.FieldSatisfaction, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(conversation.FieldLastActiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(conversation.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(conversation.FieldClosedAt, field.TypeTime)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationUpdateOne is the builder for updating a single Conversation entity.
type ConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdateOne) SetUpdatedAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTicketNo sets the "ticket_no" field.
func (_u *ConversationUpdateOne) SetTicketNo(v string) *ConversationUpdateOne {
	_u.mutation.SetTicketNo(v)
	return _u
}

// SetNillableTicketNo sets the "ticket_no" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableTicketNo(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetTicketNo(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ConversationUpdateOne) SetSubject(v string) *ConversationUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSubject(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetPreview sets the "preview" field.
func (_u *ConversationUpdateOne) SetPreview(v string) *ConversationUpdateOne {
	_u.mutation.SetPreview(v)
	return _u
}

// SetNillablePreview sets the "preview" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillablePreview(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetPreview(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *ConversationUpdateOne) SetChannel(v string) *ConversationUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableChannel(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetQueue sets the "queue" field.
func (_u *ConversationUpdateOne) SetQueue(v string) *ConversationUpdateOne {
	_u.mutation.SetQueue(v)
	return _u
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableQueue(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetQueue(*v)
	}
	return _u
}

// SetAssignee sets the "assignee" field.
func (_u *ConversationUpdateOne) SetAssignee(v string) *ConversationUpdateOne {
	_u.mutation.SetAssignee(v)
	return _u
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableAssignee(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetAssignee(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdateOne) SetStatus(v string) *ConversationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableStatus(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ConversationUpdateOne) SetPriority(v string) *ConversationUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillablePriority(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetUnread sets the "unread" field.
func (_u *ConversationUpdateOne) SetUnread(v int) *ConversationUpdateOne {
	_u.mutation.ResetUnread()
	_u.mutation.SetUnread(v)
	return _u
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableUnread(v *int) *ConversationUpdateOne {
	if v != nil {
		_u.SetUnread(*v)
	}
	return _u
}

// AddUnread adds value to the "unread" field.
func (_u *ConversationUpdateOne) AddUnread(v int) *ConversationUpdateOne {
	_u.mutation.AddUnread(v)
	return _u
}

// SetSLA sets the "sla" field.
func (_u *ConversationUpdateOne) SetSLA(v string) *ConversationUpdateOne {
	_u.mutation.SetSLA(v)
	return _u
}

// SetNillableSLA sets the "sla" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSLA(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSLA(*v)
	}
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *ConversationUpdateOne) SetCustomerName(v string) *ConversationUpdateOne {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCustomerName(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// SetCustomerCompany sets the "customer_company" field.
func (_u *ConversationUpdateOne) SetCustomerCompany(v string) *ConversationUpdateOne {
	_u.mutation.SetCustomerCompany(v)
	return _u
}

// SetNillableCustomerCompany sets the "customer_company" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCustomerCompany(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCustomerCompany(*v)
	}
	return _u
}

// SetCustomerContact sets the "customer_contact" field.
func (_u *ConversationUpdateOne) SetCustomerContact(v string) *ConversationUpdateOne {
	_u.mutation.SetCustomerContact(v)
	return _u
}

// SetNillableCustomerContact sets the "customer_contact" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCustomerContact(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCustomerContact(*v)
	}
	return _u
}

// SetCustomerTags sets the "customer_tags" field.
func (_u *ConversationUpdateOne) SetCustomerTags(v []string) *ConversationUpdateOne {
	_u.mutation.SetCustomerTags(v)
	return _u
}

// AppendCustomerTags appends value to the "customer_tags" field.
func (_u *ConversationUpdateOne) AppendCustomerTags(v []string) *ConversationUpdateOne {
	_u.mutation.AppendCustomerTags(v)
	return _u
}

// SetCustomerPresence sets the "customer_presence" field.
func (_u *ConversationUpdateOne) SetCustomerPresence(v string) *ConversationUpdateOne {
	_u.mutation.SetCustomerPresence(v)
	return _u
}

// SetNillableCustomerPresence sets the "customer_presence" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCustomerPresence(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCustomerPresence(*v)
	}
	return _u
}

// SetCustomerTier sets the "customer_tier" field.
func (_u *ConversationUpdateOne) SetCustomerTier(v string) *ConversationUpdateOne {
	_u.mutation.SetCustomerTier(v)
	return _u
}

// SetNillableCustomerTier sets the "customer_tier" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableCustomerTier(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetCustomerTier(*v)
	}
	return _u
}

// SetLastOrder sets the "last_order" field.
func (_u *ConversationUpdateOne) SetLastOrder(v string) *ConversationUpdateOne {
	_u.mutation.SetLastOrder(v)
	return _u
}

// SetNillableLastOrder sets the "last_order" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastOrder(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastOrder(*v)
	}
	return _u
}

// SetOpenTickets sets the "open_tickets" field.
func (_u *ConversationUpdateOne) SetOpenTickets(v int) *ConversationUpdateOne {
	_u.mutation.ResetOpenTickets()
	_u.mutation.SetOpenTickets(v)
	return _u
}

// SetNillableOpenTickets sets the "open_tickets" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableOpenTickets(v *int) *ConversationUpdateOne {
	if v != nil {
		_u.SetOpenTickets(*v)
	}
	return _u
}

// AddOpenTickets adds value to the "open_tickets" field.
func (_u *ConversationUpdateOne) AddOpenTickets(v int) *ConversationUpdateOne {
	_u.mutation.AddOpenTickets(v)
	return _u
}

// SetSatisfaction sets the "satisfaction" field.
func (_u *ConversationUpdateOne) SetSatisfaction(v string) *ConversationUpdateOne {
	_u.mutation.SetSatisfaction(v)
	return _u
}

// SetNillableSatisfaction sets the "satisfaction" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSatisfaction(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSatisfaction(*v)
	}
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *ConversationUpdateOne) SetLastActiveAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastActiveAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *ConversationUpdateOne) SetClosedAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableClosedAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *ConversationUpdateOne) ClearClosedAt() *ConversationUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_u *ConversationUpdateOne) AddMessageIDs(ids ...int) *ConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdateOne) AddMessages(v ...*ConversationMessage) *ConversationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdateOne) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearMessages clears all "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdateOne) ClearMessages() *ConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ConversationMessage entities by IDs.
func (_u *ConversationUpdateOne) RemoveMessageIDs(ids ...int) *ConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ConversationMessage entities.
func (_u *ConversationUpdateOne) RemoveMessages(v ...*ConversationMessage) *ConversationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdateOne) Where(ps ...predicate.Conversation) *ConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationUpdateOne) Select(field string, fields ...string) *ConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Conversation entity.
func (_u *ConversationUpdateOne) Save(ctx context.Context) (*Conversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdateOne) SaveX(ctx context.Context) *Conversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdateOne) check() error {
	if v, ok := _u.mutation.TicketNo(); ok {
		if err := conversation.TicketNoValidator(v); err != nil {
			return &ValidationError{Name: "ticket_no", err: fmt.Errorf(`ent: validator failed for field "Conversation.ticket_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomerName(); ok {
		if err := conversation.CustomerNameValidator(v); err != nil {
			return &ValidationError{Name: "customer_name", err: fmt.Errorf(`ent: validator failed for field "Conversation.customer_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ConversationUpdateOne) sqlSave(ctx context.Context) (_node *Conversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Conversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversation.FieldID)
		for _, f := range fields {
			if !conversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TicketNo(); ok {
		_spec.SetField(conversation.FieldTicketNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Preview(); ok {
		_spec.SetField(conversation.FieldPreview, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(conversation.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Queue(); ok {
		_spec.SetField(conversation.FieldQueue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Assignee(); ok {
		_spec.SetField(conversation.FieldAssignee, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Unread(); ok {
		_spec.SetField(conversation.FieldUnread, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnread(); ok {
		_spec.AddField(conversation.FieldUnread, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SLA(); ok {
		_spec.SetField(conversation.FieldSLA, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(conversation.FieldCustomerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerCompany(); ok {
		_spec.SetField(conversation.FieldCustomerCompany, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerContact(); ok {
		_spec.SetField(conversation.FieldCustomerContact, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerTags(); ok {
		_spec.SetField(conversation.FieldCustomerTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCustomerTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversation.FieldCustomerTags, value)
		})
	}
	if value, ok := _u.mutation.CustomerPresence(); ok {
		_spec.SetField(conversation.FieldCustomerPresence, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerTier(); ok {
		_spec.SetField(conversation.FieldCustomerTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastOrder(); ok {
		_spec.SetField(conversation.FieldLastOrder, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenTickets(); ok {
		_spec.SetField(conversation.FieldOpenTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOpenTickets(); ok {
		_spec.AddField(conversation.FieldOpenTickets, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Satisfaction(); ok {
		_spec.SetField(conversation.FieldSatisfaction, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(conversation.FieldLastActiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(conversation.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(conversation.FieldClosedAt, field.TypeTime)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Conversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
