// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
)

// ConversationMessageCreate is the builder for creating a ConversationMessage entity.
type ConversationMessageCreate struct {
	config
	mutation *ConversationMessageMutation
	hooks    []Hook
}

// SetConversationID sets the "conversation_id" field.
func (_c *ConversationMessageCreate) SetConversationID(v int) *ConversationMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *ConversationMessageCreate) SetActor(v string) *ConversationMessageCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableActor(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// SetActorType sets the "actor_type" field.
func (_c *ConversationMessageCreate) SetActorType(v string) *ConversationMessageCreate {
	_c.mutation.SetActorType(v)
	return _c
}

// SetNillableActorType sets the "actor_type" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableActorType(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetActorType(*v)
	}
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *ConversationMessageCreate) SetMessageType(v string) *ConversationMessageCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableMessageType(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ConversationMessageCreate) SetContent(v string) *ConversationMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableContent(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationMessageCreate) SetCreatedAt(v time.Time) *ConversationMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableCreatedAt(v *time.Time) *ConversationMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *ConversationMessageCreate) SetConversation(v *Conversation) *ConversationMessageCreate {
	return _c.SetConversationID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_c *ConversationMessageCreate) Mutation() *ConversationMessageMutation {
	return _c.mutation
}

// Save creates the ConversationMessage in the database.
func (_c *ConversationMessageCreate) Save(ctx context.Context) (*ConversationMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationMessageCreate) SaveX(ctx context.Context) *ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationMessageCreate) defaults() {
	if _, ok := _c.mutation.Actor(); !ok {
		v := conversationmessage.DefaultActor
		_c.mutation.SetActor(v)
	}
	if _, ok := _c.mutation.ActorType(); !ok {
		v := conversationmessage.DefaultActorType
		_c.mutation.SetActorType(v)
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		v := conversationmessage.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := conversationmessage.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationMessageCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ConversationMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "ConversationMessage.actor"`)}
	}
	if _, ok := _c.mutation.ActorType(); !ok {
		return &ValidationError{Name: "actor_type", err: errors.New(`ent: missing required field "ConversationMessage.actor_type"`)}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "ConversationMessage.message_type"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ConversationMessage.content"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationMessage.created_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "ConversationMessage.conversation"`)}
	}
	return nil
}

func (_c *ConversationMessageCreate) sqlSave(ctx context.Context) (*ConversationMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationMessageCreate) createSpec() (*ConversationMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationmessage.Table, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(conversationmessage.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.ActorType(); ok {
		_spec.SetField(conversationmessage.FieldActorType, field.TypeString, value)
		_node.ActorType = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationMessageCreateBulk is the builder for creating many ConversationMessage entities in bulk.
type ConversationMessageCreateBulk struct {
	config
	err      error
	builders []*ConversationMessageCreate
}

// Save creates the ConversationMessage entities in the database.
func (_c *ConversationMessageCreateBulk) Save(ctx context.Context) ([]*ConversationMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) SaveX(ctx context.Context) []*ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
