// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationCreate) SetCreatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCreatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationCreate) SetUpdatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUpdatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTicketNo sets the "ticket_no" field.
func (_c *ConversationCreate) SetTicketNo(v string) *ConversationCreate {
	_c.mutation.SetTicketNo(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *ConversationCreate) SetSubject(v string) *ConversationCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetPreview sets the "preview" field.
func (_c *ConversationCreate) SetPreview(v string) *ConversationCreate {
	_c.mutation.SetPreview(v)
	return _c
}

// SetNillablePreview sets the "preview" field if the given value is not nil.
func (_c *ConversationCreate) SetNillablePreview(v *string) *ConversationCreate {
	if v != nil {
		_c.SetPreview(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *ConversationCreate) SetChannel(v string) *ConversationCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableChannel(v *string) *ConversationCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetQueue sets the "queue" field.
func (_c *ConversationCreate) SetQueue(v string) *ConversationCreate {
	_c.mutation.SetQueue(v)
	return _c
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableQueue(v *string) *ConversationCreate {
	if v != nil {
		_c.SetQueue(*v)
	}
	return _c
}

// SetAssignee sets the "assignee" field.
func (_c *ConversationCreate) SetAssignee(v string) *ConversationCreate {
	_c.mutation.SetAssignee(v)
	return _c
}

// SetNillableAssignee sets the "assignee" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableAssignee(v *string) *ConversationCreate {
	if v != nil {
		_c.SetAssignee(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConversationCreate) SetStatus(v string) *ConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableStatus(v *string) *ConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ConversationCreate) SetPriority(v string) *ConversationCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ConversationCreate) SetNillablePriority(v *string) *ConversationCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetUnread sets the "unread" field.
func (_c *ConversationCreate) SetUnread(v int) *ConversationCreate {
	_c.mutation.SetUnread(v)
	return _c
}

// SetNillableUnread sets the "unread" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUnread(v *int) *ConversationCreate {
	if v != nil {
		_c.SetUnread(*v)
	}
	return _c
}

// SetSLA sets the "sla" field.
func (_c *ConversationCreate) SetSLA(v string) *ConversationCreate {
	_c.mutation.SetSLA(v)
	return _c
}

// SetNillableSLA sets the "sla" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableSLA(v *string) *ConversationCreate {
	if v != nil {
		_c.SetSLA(*v)
	}
	return _c
}

// SetCustomerName sets the "customer_name" field.
func (_c *ConversationCreate) SetCustomerName(v string) *ConversationCreate {
	_c.mutation.SetCustomerName(v)
	return _c
}

// SetCustomerCompany sets the "customer_company" field.
func (_c *ConversationCreate) SetCustomerCompany(v string) *ConversationCreate {
	_c.mutation.SetCustomerCompany(v)
	return _c
}

// SetNillableCustomerCompany sets the "customer_company" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCustomerCompany(v *string) *ConversationCreate {
	if v != nil {
		_c.SetCustomerCompany(*v)
	}
	return _c
}

// SetCustomerContact sets the "customer_contact" field.
func (_c *ConversationCreate) SetCustomerContact(v string) *ConversationCreate {
	_c.mutation.SetCustomerContact(v)
	return _c
}

// SetNillableCustomerContact sets the "customer_contact" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCustomerContact(v *string) *ConversationCreate {
	if v != nil {
		_c.SetCustomerContact(*v)
	}
	return _c
}

// SetCustomerTags sets the "customer_tags" field.
func (_c *ConversationCreate) SetCustomerTags(v []string) *ConversationCreate {
	_c.mutation.SetCustomerTags(v)
	return _c
}

// SetCustomerPresence sets the "customer_presence" field.
func (_c *ConversationCreate) SetCustomerPresence(v string) *ConversationCreate {
	_c.mutation.SetCustomerPresence(v)
	return _c
}

// SetNillableCustomerPresence sets the "customer_presence" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCustomerPresence(v *string) *ConversationCreate {
	if v != nil {
		_c.SetCustomerPresence(*v)
	}
	return _c
}

// SetCustomerTier sets the "customer_tier" field.
func (_c *ConversationCreate) SetCustomerTier(v string) *ConversationCreate {
	_c.mutation.SetCustomerTier(v)
	return _c
}

// SetNillableCustomerTier sets the "customer_tier" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCustomerTier(v *string) *ConversationCreate {
	if v != nil {
		_c.SetCustomerTier(*v)
	}
	return _c
}

// SetLastOrder sets the "last_order" field.
func (_c *ConversationCreate) SetLastOrder(v string) *ConversationCreate {
	_c.mutation.SetLastOrder(v)
	return _c
}

// SetNillableLastOrder sets the "last_order" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastOrder(v *string) *ConversationCreate {
	if v != nil {
		_c.SetLastOrder(*v)
	}
	return _c
}

// SetOpenTickets sets the "open_tickets" field.
func (_c *ConversationCreate) SetOpenTickets(v int) *ConversationCreate {
	_c.mutation.SetOpenTickets(v)
	return _c
}

// SetNillableOpenTickets sets the "open_tickets" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableOpenTickets(v *int) *ConversationCreate {
	if v != nil {
		_c.SetOpenTickets(*v)
	}
	return _c
}

// SetSatisfaction sets the "satisfaction" field.
func (_c *ConversationCreate) SetSatisfaction(v string) *ConversationCreate {
	_c.mutation.SetSatisfaction(v)
	return _c
}

// SetNillableSatisfaction sets the "satisfaction" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableSatisfaction(v *string) *ConversationCreate {
	if v != nil {
		_c.SetSatisfaction(*v)
	}
	return _c
}

// SetLastActiveAt sets the "last_active_at" field.
func (_c *ConversationCreate) SetLastActiveAt(v time.Time) *ConversationCreate {
	_c.mutation.SetLastActiveAt(v)
	return _c
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastActiveAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetLastActiveAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *ConversationCreate) SetClosedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableClosedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_c *ConversationCreate) AddMessageIDs(ids ...int) *ConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_c *ConversationCreate) AddMessages(v ...*ConversationMessage) *ConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_c *ConversationCreate) Mutation() *ConversationMutation {
	return _c.mutation
}

// Save creates the Conversation in the database.
func (_c *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Preview(); !ok {
		v := conversation.DefaultPreview
		_c.mutation.SetPreview(v)
	}
	if _, ok := _c.mutation.Channel(); !ok {
		v := conversation.DefaultChannel
		_c.mutation.SetChannel(v)
	}
	if _, ok := _c.mutation.Queue(); !ok {
		v := conversation.DefaultQueue
		_c.mutation.SetQueue(v)
	}
	if _, ok := _c.mutation.Assignee(); !ok {
		v := conversation.DefaultAssignee
		_c.mutation.SetAssignee(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := conversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := conversation.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Unread(); !ok {
		v := conversation.DefaultUnread
		_c.mutation.SetUnread(v)
	}
	if _, ok := _c.mutation.SLA(); !ok {
		v := conversation.DefaultSLA
		_c.mutation.SetSLA(v)
	}
	if _, ok := _c.mutation.CustomerCompany(); !ok {
		v := conversation.DefaultCustomerCompany
		_c.mutation.SetCustomerCompany(v)
	}
	if _, ok := _c.mutation.CustomerContact(); !ok {
		v := conversation.DefaultCustomerContact
		_c.mutation.SetCustomerContact(v)
	}
	if _, ok := _c.mutation.CustomerTags(); !ok {
		v := conversation.DefaultCustomerTags
		_c.mutation.SetCustomerTags(v)
	}
	if _, ok := _c.mutation.CustomerPresence(); !ok {
		v := conversation.DefaultCustomerPresence
		_c.mutation.SetCustomerPresence(v)
	}
	if _, ok := _c.mutation.CustomerTier(); !ok {
		v := conversation.DefaultCustomerTier
		_c.mutation.SetCustomerTier(v)
	}
	if _, ok := _c.mutation.LastOrder(); !ok {
		v := conversation.DefaultLastOrder
		_c.mutation.SetLastOrder(v)
	}
	if _, ok := _c.mutation.OpenTickets(); !ok {
		v := conversation.DefaultOpenTickets
		_c.mutation.SetOpenTickets(v)
	}
	if _, ok := _c.mutation.Satisfaction(); !ok {
		v := conversation.DefaultSatisfaction
		_c.mutation.SetSatisfaction(v)
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		v := conversation.DefaultLastActiveAt()
		_c.mutation.SetLastActiveAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := _c.mutation.TicketNo(); !ok {
		return &ValidationError{Name: "ticket_no", err: errors.New(`ent: missing required field "Conversation.ticket_no"`)}
	}
	if v, ok := _c.mutation.TicketNo(); ok {
		if err := conversation.TicketNoValidator(v); err != nil {
			return &ValidationError{Name: "ticket_no", err: fmt.Errorf(`ent: validator failed for field "Conversation.ticket_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Conversation.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Preview(); !ok {
		return &ValidationError{Name: "preview", err: errors.New(`ent: missing required field "Conversation.preview"`)}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "Conversation.channel"`)}
	}
	if _, ok := _c.mutation.Queue(); !ok {
		return &ValidationError{Name: "queue", err: errors.New(`ent: missing required field "Conversation.queue"`)}
	}
	if _, ok := _c.mutation.Assignee(); !ok {
		return &ValidationError{Name: "assignee", err: errors.New(`ent: missing required field "Conversation.assignee"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Conversation.status"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Conversation.priority"`)}
	}
	if _, ok := _c.mutation.Unread(); !ok {
		return &ValidationError{Name: "unread", err: errors.New(`ent: missing required field "Conversation.unread"`)}
	}
	if _, ok := _c.mutation.SLA(); !ok {
		return &ValidationError{Name: "sla", err: errors.New(`ent: missing required field "Conversation.sla"`)}
	}
	if _, ok := _c.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "Conversation.customer_name"`)}
	}
	if v, ok := _c.mutation.CustomerName(); ok {
		if err := conversation.CustomerNameValidator(v); err != nil {
			return &ValidationError{Name: "customer_name", err: fmt.Errorf(`ent: validator failed for field "Conversation.customer_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomerCompany(); !ok {
		return &ValidationError{Name: "customer_company", err: errors.New(`ent: missing required field "Conversation.customer_company"`)}
	}
	if _, ok := _c.mutation.CustomerContact(); !ok {
		return &ValidationError{Name: "customer_contact", err: errors.New(`ent: missing required field "Conversation.customer_contact"`)}
	}
	if _, ok := _c.mutation.CustomerTags(); !ok {
		return &ValidationError{Name: "customer_tags", err: errors.New(`ent: missing required field "Conversation.customer_tags"`)}
	}
	if _, ok := _c.mutation.CustomerPresence(); !ok {
		return &ValidationError{Name: "customer_presence", err: errors.New(`ent: missing required field "Conversation.customer_presence"`)}
	}
	if _, ok := _c.mutation.CustomerTier(); !ok {
		return &ValidationError{Name: "customer_tier", err: errors.New(`ent: missing required field "Conversation.customer_tier"`)}
	}
	if _, ok := _c.mutation.LastOrder(); !ok {
		return &ValidationError{Name: "last_order", err: errors.New(`ent: missing required field "Conversation.last_order"`)}
	}
	if _, ok := _c.mutation.OpenTickets(); !ok {
		return &ValidationError{Name: "open_tickets", err: errors.New(`ent: missing required field "Conversation.open_tickets"`)}
	}
	if _, ok := _c.mutation.Satisfaction(); !ok {
		return &ValidationError{Name: "satisfaction", err: errors.New(`ent: missing required field "Conversation.satisfaction"`)}
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		return &ValidationError{Name: "last_active_at", err: errors.New(`ent: missing required field "Conversation.last_active_at"`)}
	}
	return nil
}

func (_c *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TicketNo(); ok {
		_spec.SetField(conversation.FieldTicketNo, field.TypeString, value)
		_node.TicketNo = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Preview(); ok {
		_spec.SetField(conversation.FieldPreview, field.TypeString, value)
		_node.Preview = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(conversation.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Queue(); ok {
		_spec.SetField(conversation.FieldQueue, field.TypeString, value)
		_node.Queue = value
	}
	if value, ok := _c.mutation.Assignee(); ok {
		_spec.SetField(conversation.FieldAssignee, field.TypeString, value)
		_node.Assignee = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Unread(); ok {
		_spec.SetField(conversation.FieldUnread, field.TypeInt, value)
		_node.Unread = value
	}
	if value, ok := _c.mutation.SLA(); ok {
		_spec.SetField(conversation.FieldSLA, field.TypeString, value)
		_node.SLA = value
	}
	if value, ok := _c.mutation.CustomerName(); ok {
		_spec.SetField(conversation.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := _c.mutation.CustomerCompany(); ok {
		_spec.SetField(conversation.FieldCustomerCompany, field.TypeString, value)
		_node.CustomerCompany = value
	}
	if value, ok := _c.mutation.CustomerContact(); ok {
		_spec.SetField(conversation.FieldCustomerContact, field.TypeString, value)
		_node.CustomerContact = value
	}
	if value, ok := _c.mutation.CustomerTags(); ok {
		_spec.SetField(conversation.FieldCustomerTags, field.TypeJSON, value)
		_node.CustomerTags = value
	}
	if value, ok := _c.mutation.CustomerPresence(); ok {
		_spec.SetField(conversation.FieldCustomerPresence, field.TypeString, value)
		_node.CustomerPresence = value
	}
	if value, ok := _c.mutation.CustomerTier(); ok {
		_spec.SetField(conversation.FieldCustomerTier, field.TypeString, value)
		_node.CustomerTier = value
	}
	if value, ok := _c.mutation.LastOrder(); ok {
		_spec.SetField(conversation.FieldLastOrder, field.TypeString, value)
		_node.LastOrder = value
	}
	if value, ok := _c.mutation.OpenTickets(); ok {
		_spec.SetField(conversation.FieldOpenTickets, field.TypeInt, value)
		_node.OpenTickets = value
	}
	if value, ok := _c.mutation.Satisfaction(); ok {
		_spec.SetField(conversation.FieldSatisfaction, field.TypeString, value)
		_node.Satisfaction = value
	}
	if value, ok := _c.mutation.LastActiveAt(); ok {
		_spec.SetField(conversation.FieldLastActiveAt, field.TypeTime, value)
		_node.LastActiveAt = value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(conversation.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
}

// Save creates the Conversation entities in the database.
func (_c *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Conversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
