// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
)

// Conversation is the model entity for the Conversation schema.
type Conversation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TicketNo holds the value of the "ticket_no" field.
	TicketNo string `json:"ticket_no,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Preview holds the value of the "preview" field.
	Preview string `json:"preview,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// Queue holds the value of the "queue" field.
	Queue string `json:"queue,omitempty"`
	// Assignee holds the value of the "assignee" field.
	Assignee string `json:"assignee,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// Unread holds the value of the "unread" field.
	Unread int `json:"unread,omitempty"`
	// SLA holds the value of the "sla" field.
	SLA string `json:"sla,omitempty"`
	// CustomerName holds the value of the "customer_name" field.
	CustomerName string `json:"customer_name,omitempty"`
	// CustomerCompany holds the value of the "customer_company" field.
	CustomerCompany string `json:"customer_company,omitempty"`
	// CustomerContact holds the value of the "customer_contact" field.
	CustomerContact string `json:"customer_contact,omitempty"`
	// CustomerTags holds the value of the "customer_tags" field.
	CustomerTags []string `json:"customer_tags,omitempty"`
	// CustomerPresence holds the value of the "customer_presence" field.
	CustomerPresence string `json:"customer_presence,omitempty"`
	// CustomerTier holds the value of the "customer_tier" field.
	CustomerTier string `json:"customer_tier,omitempty"`
	// LastOrder holds the value of the "last_order" field.
	LastOrder string `json:"last_order,omitempty"`
	// OpenTickets holds the value of the "open_tickets" field.
	OpenTickets int `json:"open_tickets,omitempty"`
	// Satisfaction holds the value of the "satisfaction" field.
	Satisfaction string `json:"satisfaction,omitempty"`
	// LastActiveAt holds the value of the "last_active_at" field.
	LastActiveAt time.Time `json:"last_active_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationQuery when eager-loading is set.
	Edges        ConversationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationEdges holds the relations/edges for other nodes in the graph.
type ConversationEdges struct {
	// Messages holds the value of the messages edge.
	Messages []*ConversationMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) MessagesOrErr() ([]*ConversationMessage, error) {
	if e.loadedTypes[0] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Conversation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversation.FieldCustomerTags:
			values[i] = new([]byte)
		case conversation.FieldID, conversation.FieldUnread, conversation.FieldOpenTickets:
			values[i] = new(sql.NullInt64)
		case conversation.FieldTicketNo, conversation.FieldSubject, conversation.FieldPreview, conversation.FieldChannel, conversation.FieldQueue, conversation.FieldAssignee, conversation.FieldStatus, conversation.FieldPriority, conversation.FieldSLA, conversation.FieldCustomerName, conversation.FieldCustomerCompany, conversation.FieldCustomerContact, conversation.FieldCustomerPresence, conversation.FieldCustomerTier, conversation.FieldLastOrder, conversation.FieldSatisfaction:
			values[i] = new(sql.NullString)
		case conversation.FieldCreatedAt, conversation.FieldUpdatedAt, conversation.FieldLastActiveAt, conversation.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Conversation fields.
func (_m *Conversation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case conversation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case conversation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case conversation.FieldTicketNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_no", values[i])
			} else if value.Valid {
				_m.TicketNo = value.String
			}
		case conversation.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case conversation.FieldPreview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview", values[i])
			} else if value.Valid {
				_m.Preview = value.String
			}
		case conversation.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case conversation.FieldQueue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field queue", values[i])
			} else if value.Valid {
				_m.Queue = value.String
			}
		case conversation.FieldAssignee:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assignee", values[i])
			} else if value.Valid {
				_m.Assignee = value.String
			}
		case conversation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case conversation.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case conversation.FieldUnread:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unread", values[i])
			} else if value.Valid {
				_m.Unread = int(value.Int64)
			}
		case conversation.FieldSLA:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sla", values[i])
			} else if value.Valid {
				_m.SLA = value.String
			}
		case conversation.FieldCustomerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_name", values[i])
			} else if value.Valid {
				_m.CustomerName = value.String
			}
		case conversation.FieldCustomerCompany:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_company", values[i])
			} else if value.Valid {
				_m.CustomerCompany = value.String
			}
		case conversation.FieldCustomerContact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_contact", values[i])
			} else if value.Valid {
				_m.CustomerContact = value.String
			}
		case conversation.FieldCustomerTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field customer_tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CustomerTags); err != nil {
					return fmt.Errorf("unmarshal field customer_tags: %w", err)
				}
			}
		case conversation.FieldCustomerPresence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_presence", values[i])
			} else if value.Valid {
				_m.CustomerPresence = value.String
			}
		case conversation.FieldCustomerTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_tier", values[i])
			} else if value.Valid {
				_m.CustomerTier = value.String
			}
		case conversation.FieldLastOrder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_order", values[i])
			} else if value.Valid {
				_m.LastOrder = value.String
			}
		case conversation.FieldOpenTickets:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field open_tickets", values[i])
			} else if value.Valid {
				_m.OpenTickets = int(value.Int64)
			}
		case conversation.FieldSatisfaction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field satisfaction", values[i])
			} else if value.Valid {
				_m.Satisfaction = value.String
			}
		case conversation.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = value.Time
			}
		case conversation.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Conversation.
// This includes values selected through modifiers, order, etc.
func (_m *Conversation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMessages queries the "messages" edge of the Conversation entity.
func (_m *Conversation) QueryMessages() *ConversationMessageQuery {
	return NewConversationClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this Conversation.
// Note that you need to call Conversation.Unwrap() before calling this method if this Conversation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Conversation) Update() *ConversationUpdateOne {
	return NewConversationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Conversation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Conversation) Unwrap() *Conversation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Conversation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Conversation) String() string {
	var builder strings.Builder
	builder.WriteString("Conversation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ticket_no=")
	builder.WriteString(_m.TicketNo)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("preview=")
	builder.WriteString(_m.Preview)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("queue=")
	builder.WriteString(_m.Queue)
	builder.WriteString(", ")
	builder.WriteString("assignee=")
	builder.WriteString(_m.Assignee)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("unread=")
	builder.WriteString(fmt.Sprintf("%v", _m.Unread))
	builder.WriteString(", ")
	builder.WriteString("sla=")
	builder.WriteString(_m.SLA)
	builder.WriteString(", ")
	builder.WriteString("customer_name=")
	builder.WriteString(_m.CustomerName)
	builder.WriteString(", ")
	builder.WriteString("customer_company=")
	builder.WriteString(_m.CustomerCompany)
	builder.WriteString(", ")
	builder.WriteString("customer_contact=")
	builder.WriteString(_m.CustomerContact)
	builder.WriteString(", ")
	builder.WriteString("customer_tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomerTags))
	builder.WriteString(", ")
	builder.WriteString("customer_presence=")
	builder.WriteString(_m.CustomerPresence)
	builder.WriteString(", ")
	builder.WriteString("customer_tier=")
	builder.WriteString(_m.CustomerTier)
	builder.WriteString(", ")
	builder.WriteString("last_order=")
	builder.WriteString(_m.LastOrder)
	builder.WriteString(", ")
	builder.WriteString("open_tickets=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpenTickets))
	builder.WriteString(", ")
	builder.WriteString("satisfaction=")
	builder.WriteString(_m.Satisfaction)
	builder.WriteString(", ")
	builder.WriteString("last_active_at=")
	builder.WriteString(_m.LastActiveAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Conversations is a parsable slice of Conversation.
type Conversations []*Conversation
