// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Wei-Shaw/sub2api/ent/auditlog"
	"github.com/Wei-Shaw/sub2api/ent/menu"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/schema"
	"github.com/Wei-Shaw/sub2api/ent/systemconfig"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescUsername is the schema descriptor for username field.
	auditlogDescUsername := auditlogFields[0].Descriptor()
	// auditlog.DefaultUsername holds the default value on creation for the username field.
	auditlog.DefaultUsername = auditlogDescUsername.Default.(string)
	// auditlogDescModule is the schema descriptor for module field.
	auditlogDescModule := auditlogFields[1].Descriptor()
	// auditlog.DefaultModule holds the default value on creation for the module field.
	auditlog.DefaultModule = auditlogDescModule.Default.(string)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.DefaultAction holds the default value on creation for the action field.
	auditlog.DefaultAction = auditlogDescAction.Default.(string)
	// auditlogDescMethod is the schema descriptor for method field.
	auditlogDescMethod := auditlogFields[3].Descriptor()
	// auditlog.DefaultMethod holds the default value on creation for the method field.
	auditlog.DefaultMethod = auditlogDescMethod.Default.(string)
	// auditlogDescPath is the schema descriptor for path field.
	auditlogDescPath := auditlogFields[4].Descriptor()
	// auditlog.DefaultPath holds the default value on creation for the path field.
	auditlog.DefaultPath = auditlogDescPath.Default.(string)
	// auditlogDescStatusCode is the schema descriptor for status_code field.
	auditlogDescStatusCode := auditlogFields[5].Descriptor()
	// auditlog.DefaultStatusCode holds the default value on creation for the status_code field.
	auditlog.DefaultStatusCode = auditlogDescStatusCode.Default.(int)
	// auditlogDescIP is the schema descriptor for ip field.
	auditlogDescIP := auditlogFields[6].Descriptor()
	// auditlog.DefaultIP holds the default value on creation for the ip field.
	auditlog.DefaultIP = auditlogDescIP.Default.(string)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[7].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[8].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[0].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescTitle is the schema descriptor for title field.
	menuDescTitle := menuFields[0].Descriptor()
	// menu.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	menu.TitleValidator = menuDescTitle.Validators[0].(func(string) error)
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[1].Descriptor()
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = menuDescName.Validators[0].(func(string) error)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[2].Descriptor()
	// menu.PathValidator is a validator for the "path" field. It is called by the builders before save.
	menu.PathValidator = menuDescPath.Validators[0].(func(string) error)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[3].Descriptor()
	// menu.DefaultComponent holds the default value on creation for the component field.
	menu.DefaultComponent = menuDescComponent.Default.(string)
	// menuDescIcon is the schema descriptor for icon field.
	menuDescIcon := menuFields[4].Descriptor()
	// menu.DefaultIcon holds the default value on creation for the icon field.
	menu.DefaultIcon = menuDescIcon.Default.(string)
	// menuDescMenuType is the schema descriptor for menu_type field.
	menuDescMenuType := menuFields[5].Descriptor()
	// menu.DefaultMenuType holds the default value on creation for the menu_type field.
	menu.DefaultMenuType = menuDescMenuType.Default.(string)
	// menuDescPermission is the schema descriptor for permission field.
	menuDescPermission := menuFields[6].Descriptor()
	// menu.DefaultPermission holds the default value on creation for the permission field.
	menu.DefaultPermission = menuDescPermission.Default.(string)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuFields[7].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(int)
	// menuDescHidden is the schema descriptor for hidden field.
	menuDescHidden := menuFields[8].Descriptor()
	// menu.DefaultHidden holds the default value on creation for the hidden field.
	menu.DefaultHidden = menuDescHidden.Default.(bool)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = roleDescCode.Validators[0].(func(string) error)
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// roleDescPermissions is the schema descriptor for permissions field.
	roleDescPermissions := roleFields[3].Descriptor()
	// role.DefaultPermissions holds the default value on creation for the permissions field.
	role.DefaultPermissions = roleDescPermissions.Default.([]string)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[4].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	systemconfigMixin := schema.SystemConfig{}.Mixin()
	systemconfigMixinFields0 := systemconfigMixin[0].Fields()
	_ = systemconfigMixinFields0
	systemconfigFields := schema.SystemConfig{}.Fields()
	_ = systemconfigFields
	// systemconfigDescCreatedAt is the schema descriptor for created_at field.
	systemconfigDescCreatedAt := systemconfigMixinFields0[0].Descriptor()
	// systemconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemconfig.DefaultCreatedAt = systemconfigDescCreatedAt.Default.(func() time.Time)
	// systemconfigDescUpdatedAt is the schema descriptor for updated_at field.
	systemconfigDescUpdatedAt := systemconfigMixinFields0[1].Descriptor()
	// systemconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemconfig.DefaultUpdatedAt = systemconfigDescUpdatedAt.Default.(func() time.Time)
	// systemconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemconfig.UpdateDefaultUpdatedAt = systemconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemconfigDescKey is the schema descriptor for key field.
	systemconfigDescKey := systemconfigFields[0].Descriptor()
	// systemconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemconfig.KeyValidator = systemconfigDescKey.Validators[0].(func(string) error)
	// systemconfigDescValue is the schema descriptor for value field.
	systemconfigDescValue := systemconfigFields[1].Descriptor()
	// systemconfig.DefaultValue holds the default value on creation for the value field.
	systemconfig.DefaultValue = systemconfigDescValue.Default.(string)
	// systemconfigDescCategory is the schema descriptor for category field.
	systemconfigDescCategory := systemconfigFields[2].Descriptor()
	// systemconfig.DefaultCategory holds the default value on creation for the category field.
	systemconfig.DefaultCategory = systemconfigDescCategory.Default.(string)
	// systemconfigDescDescription is the schema descriptor for description field.
	systemconfigDescDescription := systemconfigFields[3].Descriptor()
	// systemconfig.DefaultDescription holds the default value on creation for the description field.
	systemconfig.DefaultDescription = systemconfigDescDescription.Default.(string)
	// systemconfigDescIsPublic is the schema descriptor for is_public field.
	systemconfigDescIsPublic := systemconfigFields[4].Descriptor()
	// systemconfig.DefaultIsPublic holds the default value on creation for the is_public field.
	systemconfig.DefaultIsPublic = systemconfigDescIsPublic.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[3].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
}
