// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Wei-Shaw/sub2api/ent/auditlog"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/menu"
	"github.com/Wei-Shaw/sub2api/ent/role"
	"github.com/Wei-Shaw/sub2api/ent/schema"
	"github.com/Wei-Shaw/sub2api/ent/systemconfig"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescUsername is the schema descriptor for username field.
	auditlogDescUsername := auditlogFields[0].Descriptor()
	// auditlog.DefaultUsername holds the default value on creation for the username field.
	auditlog.DefaultUsername = auditlogDescUsername.Default.(string)
	// auditlogDescModule is the schema descriptor for module field.
	auditlogDescModule := auditlogFields[1].Descriptor()
	// auditlog.DefaultModule holds the default value on creation for the module field.
	auditlog.DefaultModule = auditlogDescModule.Default.(string)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.DefaultAction holds the default value on creation for the action field.
	auditlog.DefaultAction = auditlogDescAction.Default.(string)
	// auditlogDescMethod is the schema descriptor for method field.
	auditlogDescMethod := auditlogFields[3].Descriptor()
	// auditlog.DefaultMethod holds the default value on creation for the method field.
	auditlog.DefaultMethod = auditlogDescMethod.Default.(string)
	// auditlogDescPath is the schema descriptor for path field.
	auditlogDescPath := auditlogFields[4].Descriptor()
	// auditlog.DefaultPath holds the default value on creation for the path field.
	auditlog.DefaultPath = auditlogDescPath.Default.(string)
	// auditlogDescStatusCode is the schema descriptor for status_code field.
	auditlogDescStatusCode := auditlogFields[5].Descriptor()
	// auditlog.DefaultStatusCode holds the default value on creation for the status_code field.
	auditlog.DefaultStatusCode = auditlogDescStatusCode.Default.(int)
	// auditlogDescIP is the schema descriptor for ip field.
	auditlogDescIP := auditlogFields[6].Descriptor()
	// auditlog.DefaultIP holds the default value on creation for the ip field.
	auditlog.DefaultIP = auditlogDescIP.Default.(string)
	// auditlogDescDetail is the schema descriptor for detail field.
	auditlogDescDetail := auditlogFields[7].Descriptor()
	// auditlog.DefaultDetail holds the default value on creation for the detail field.
	auditlog.DefaultDetail = auditlogDescDetail.Default.(string)
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogFields[8].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	conversationMixin := schema.Conversation{}.Mixin()
	conversationMixinFields0 := conversationMixin[0].Fields()
	_ = conversationMixinFields0
	conversationFields := schema.Conversation{}.Fields()
	_ = conversationFields
	// conversationDescCreatedAt is the schema descriptor for created_at field.
	conversationDescCreatedAt := conversationMixinFields0[0].Descriptor()
	// conversation.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversation.DefaultCreatedAt = conversationDescCreatedAt.Default.(func() time.Time)
	// conversationDescUpdatedAt is the schema descriptor for updated_at field.
	conversationDescUpdatedAt := conversationMixinFields0[1].Descriptor()
	// conversation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	conversation.DefaultUpdatedAt = conversationDescUpdatedAt.Default.(func() time.Time)
	// conversation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	conversation.UpdateDefaultUpdatedAt = conversationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// conversationDescTicketNo is the schema descriptor for ticket_no field.
	conversationDescTicketNo := conversationFields[0].Descriptor()
	// conversation.TicketNoValidator is a validator for the "ticket_no" field. It is called by the builders before save.
	conversation.TicketNoValidator = conversationDescTicketNo.Validators[0].(func(string) error)
	// conversationDescSubject is the schema descriptor for subject field.
	conversationDescSubject := conversationFields[1].Descriptor()
	// conversation.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	conversation.SubjectValidator = conversationDescSubject.Validators[0].(func(string) error)
	// conversationDescPreview is the schema descriptor for preview field.
	conversationDescPreview := conversationFields[2].Descriptor()
	// conversation.DefaultPreview holds the default value on creation for the preview field.
	conversation.DefaultPreview = conversationDescPreview.Default.(string)
	// conversationDescChannel is the schema descriptor for channel field.
	conversationDescChannel := conversationFields[3].Descriptor()
	// conversation.DefaultChannel holds the default value on creation for the channel field.
	conversation.DefaultChannel = conversationDescChannel.Default.(string)
	// conversationDescQueue is the schema descriptor for queue field.
	conversationDescQueue := conversationFields[4].Descriptor()
	// conversation.DefaultQueue holds the default value on creation for the queue field.
	conversation.DefaultQueue = conversationDescQueue.Default.(string)
	// conversationDescAssignee is the schema descriptor for assignee field.
	conversationDescAssignee := conversationFields[5].Descriptor()
	// conversation.DefaultAssignee holds the default value on creation for the assignee field.
	conversation.DefaultAssignee = conversationDescAssignee.Default.(string)
	// conversationDescStatus is the schema descriptor for status field.
	conversationDescStatus := conversationFields[6].Descriptor()
	// conversation.DefaultStatus holds the default value on creation for the status field.
	conversation.DefaultStatus = conversationDescStatus.Default.(string)
	// conversationDescPriority is the schema descriptor for priority field.
	conversationDescPriority := conversationFields[7].Descriptor()
	// conversation.DefaultPriority holds the default value on creation for the priority field.
	conversation.DefaultPriority = conversationDescPriority.Default.(string)
	// conversationDescUnread is the schema descriptor for unread field.
	conversationDescUnread := conversationFields[8].Descriptor()
	// conversation.DefaultUnread holds the default value on creation for the unread field.
	conversation.DefaultUnread = conversationDescUnread.Default.(int)
	// conversationDescSLA is the schema descriptor for sla field.
	conversationDescSLA := conversationFields[9].Descriptor()
	// conversation.DefaultSLA holds the default value on creation for the sla field.
	conversation.DefaultSLA = conversationDescSLA.Default.(string)
	// conversationDescCustomerName is the schema descriptor for customer_name field.
	conversationDescCustomerName := conversationFields[10].Descriptor()
	// conversation.CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	conversation.CustomerNameValidator = conversationDescCustomerName.Validators[0].(func(string) error)
	// conversationDescCustomerCompany is the schema descriptor for customer_company field.
	conversationDescCustomerCompany := conversationFields[11].Descriptor()
	// conversation.DefaultCustomerCompany holds the default value on creation for the customer_company field.
	conversation.DefaultCustomerCompany = conversationDescCustomerCompany.Default.(string)
	// conversationDescCustomerContact is the schema descriptor for customer_contact field.
	conversationDescCustomerContact := conversationFields[12].Descriptor()
	// conversation.DefaultCustomerContact holds the default value on creation for the customer_contact field.
	conversation.DefaultCustomerContact = conversationDescCustomerContact.Default.(string)
	// conversationDescCustomerTags is the schema descriptor for customer_tags field.
	conversationDescCustomerTags := conversationFields[13].Descriptor()
	// conversation.DefaultCustomerTags holds the default value on creation for the customer_tags field.
	conversation.DefaultCustomerTags = conversationDescCustomerTags.Default.([]string)
	// conversationDescCustomerPresence is the schema descriptor for customer_presence field.
	conversationDescCustomerPresence := conversationFields[14].Descriptor()
	// conversation.DefaultCustomerPresence holds the default value on creation for the customer_presence field.
	conversation.DefaultCustomerPresence = conversationDescCustomerPresence.Default.(string)
	// conversationDescCustomerTier is the schema descriptor for customer_tier field.
	conversationDescCustomerTier := conversationFields[15].Descriptor()
	// conversation.DefaultCustomerTier holds the default value on creation for the customer_tier field.
	conversation.DefaultCustomerTier = conversationDescCustomerTier.Default.(string)
	// conversationDescLastOrder is the schema descriptor for last_order field.
	conversationDescLastOrder := conversationFields[16].Descriptor()
	// conversation.DefaultLastOrder holds the default value on creation for the last_order field.
	conversation.DefaultLastOrder = conversationDescLastOrder.Default.(string)
	// conversationDescOpenTickets is the schema descriptor for open_tickets field.
	conversationDescOpenTickets := conversationFields[17].Descriptor()
	// conversation.DefaultOpenTickets holds the default value on creation for the open_tickets field.
	conversation.DefaultOpenTickets = conversationDescOpenTickets.Default.(int)
	// conversationDescSatisfaction is the schema descriptor for satisfaction field.
	conversationDescSatisfaction := conversationFields[18].Descriptor()
	// conversation.DefaultSatisfaction holds the default value on creation for the satisfaction field.
	conversation.DefaultSatisfaction = conversationDescSatisfaction.Default.(string)
	// conversationDescLastActiveAt is the schema descriptor for last_active_at field.
	conversationDescLastActiveAt := conversationFields[19].Descriptor()
	// conversation.DefaultLastActiveAt holds the default value on creation for the last_active_at field.
	conversation.DefaultLastActiveAt = conversationDescLastActiveAt.Default.(func() time.Time)
	conversationmessageFields := schema.ConversationMessage{}.Fields()
	_ = conversationmessageFields
	// conversationmessageDescActor is the schema descriptor for actor field.
	conversationmessageDescActor := conversationmessageFields[1].Descriptor()
	// conversationmessage.DefaultActor holds the default value on creation for the actor field.
	conversationmessage.DefaultActor = conversationmessageDescActor.Default.(string)
	// conversationmessageDescActorType is the schema descriptor for actor_type field.
	conversationmessageDescActorType := conversationmessageFields[2].Descriptor()
	// conversationmessage.DefaultActorType holds the default value on creation for the actor_type field.
	conversationmessage.DefaultActorType = conversationmessageDescActorType.Default.(string)
	// conversationmessageDescMessageType is the schema descriptor for message_type field.
	conversationmessageDescMessageType := conversationmessageFields[3].Descriptor()
	// conversationmessage.DefaultMessageType holds the default value on creation for the message_type field.
	conversationmessage.DefaultMessageType = conversationmessageDescMessageType.Default.(string)
	// conversationmessageDescContent is the schema descriptor for content field.
	conversationmessageDescContent := conversationmessageFields[4].Descriptor()
	// conversationmessage.DefaultContent holds the default value on creation for the content field.
	conversationmessage.DefaultContent = conversationmessageDescContent.Default.(string)
	// conversationmessageDescCreatedAt is the schema descriptor for created_at field.
	conversationmessageDescCreatedAt := conversationmessageFields[5].Descriptor()
	// conversationmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	conversationmessage.DefaultCreatedAt = conversationmessageDescCreatedAt.Default.(func() time.Time)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[0].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescTitle is the schema descriptor for title field.
	menuDescTitle := menuFields[0].Descriptor()
	// menu.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	menu.TitleValidator = menuDescTitle.Validators[0].(func(string) error)
	// menuDescName is the schema descriptor for name field.
	menuDescName := menuFields[1].Descriptor()
	// menu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	menu.NameValidator = menuDescName.Validators[0].(func(string) error)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[2].Descriptor()
	// menu.PathValidator is a validator for the "path" field. It is called by the builders before save.
	menu.PathValidator = menuDescPath.Validators[0].(func(string) error)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[3].Descriptor()
	// menu.DefaultComponent holds the default value on creation for the component field.
	menu.DefaultComponent = menuDescComponent.Default.(string)
	// menuDescIcon is the schema descriptor for icon field.
	menuDescIcon := menuFields[4].Descriptor()
	// menu.DefaultIcon holds the default value on creation for the icon field.
	menu.DefaultIcon = menuDescIcon.Default.(string)
	// menuDescMenuType is the schema descriptor for menu_type field.
	menuDescMenuType := menuFields[5].Descriptor()
	// menu.DefaultMenuType holds the default value on creation for the menu_type field.
	menu.DefaultMenuType = menuDescMenuType.Default.(string)
	// menuDescPermission is the schema descriptor for permission field.
	menuDescPermission := menuFields[6].Descriptor()
	// menu.DefaultPermission holds the default value on creation for the permission field.
	menu.DefaultPermission = menuDescPermission.Default.(string)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuFields[7].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(int)
	// menuDescHidden is the schema descriptor for hidden field.
	menuDescHidden := menuFields[8].Descriptor()
	// menu.DefaultHidden holds the default value on creation for the hidden field.
	menu.DefaultHidden = menuDescHidden.Default.(bool)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = roleDescCode.Validators[0].(func(string) error)
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// roleDescPermissions is the schema descriptor for permissions field.
	roleDescPermissions := roleFields[3].Descriptor()
	// role.DefaultPermissions holds the default value on creation for the permissions field.
	role.DefaultPermissions = roleDescPermissions.Default.([]string)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[4].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	systemconfigMixin := schema.SystemConfig{}.Mixin()
	systemconfigMixinFields0 := systemconfigMixin[0].Fields()
	_ = systemconfigMixinFields0
	systemconfigFields := schema.SystemConfig{}.Fields()
	_ = systemconfigFields
	// systemconfigDescCreatedAt is the schema descriptor for created_at field.
	systemconfigDescCreatedAt := systemconfigMixinFields0[0].Descriptor()
	// systemconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemconfig.DefaultCreatedAt = systemconfigDescCreatedAt.Default.(func() time.Time)
	// systemconfigDescUpdatedAt is the schema descriptor for updated_at field.
	systemconfigDescUpdatedAt := systemconfigMixinFields0[1].Descriptor()
	// systemconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemconfig.DefaultUpdatedAt = systemconfigDescUpdatedAt.Default.(func() time.Time)
	// systemconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemconfig.UpdateDefaultUpdatedAt = systemconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// systemconfigDescKey is the schema descriptor for key field.
	systemconfigDescKey := systemconfigFields[0].Descriptor()
	// systemconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	systemconfig.KeyValidator = systemconfigDescKey.Validators[0].(func(string) error)
	// systemconfigDescValue is the schema descriptor for value field.
	systemconfigDescValue := systemconfigFields[1].Descriptor()
	// systemconfig.DefaultValue holds the default value on creation for the value field.
	systemconfig.DefaultValue = systemconfigDescValue.Default.(string)
	// systemconfigDescCategory is the schema descriptor for category field.
	systemconfigDescCategory := systemconfigFields[2].Descriptor()
	// systemconfig.DefaultCategory holds the default value on creation for the category field.
	systemconfig.DefaultCategory = systemconfigDescCategory.Default.(string)
	// systemconfigDescDescription is the schema descriptor for description field.
	systemconfigDescDescription := systemconfigFields[3].Descriptor()
	// systemconfig.DefaultDescription holds the default value on creation for the description field.
	systemconfig.DefaultDescription = systemconfigDescDescription.Default.(string)
	// systemconfigDescIsPublic is the schema descriptor for is_public field.
	systemconfigDescIsPublic := systemconfigFields[4].Descriptor()
	// systemconfig.DefaultIsPublic holds the default value on creation for the is_public field.
	systemconfig.DefaultIsPublic = systemconfigDescIsPublic.Default.(bool)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[3].Descriptor()
	// user.DefaultNickname holds the default value on creation for the nickname field.
	user.DefaultNickname = userDescNickname.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[4].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
}
