// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/systemconfig"
)

// SystemConfigCreate is the builder for creating a SystemConfig entity.
type SystemConfigCreate struct {
	config
	mutation *SystemConfigMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemConfigCreate) SetCreatedAt(v time.Time) *SystemConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableCreatedAt(v *time.Time) *SystemConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemConfigCreate) SetUpdatedAt(v time.Time) *SystemConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableUpdatedAt(v *time.Time) *SystemConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *SystemConfigCreate) SetKey(v string) *SystemConfigCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *SystemConfigCreate) SetValue(v string) *SystemConfigCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableValue(v *string) *SystemConfigCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *SystemConfigCreate) SetCategory(v string) *SystemConfigCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableCategory(v *string) *SystemConfigCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SystemConfigCreate) SetDescription(v string) *SystemConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableDescription(v *string) *SystemConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *SystemConfigCreate) SetIsPublic(v bool) *SystemConfigCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *SystemConfigCreate) SetNillableIsPublic(v *bool) *SystemConfigCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// Mutation returns the SystemConfigMutation object of the builder.
func (_c *SystemConfigCreate) Mutation() *SystemConfigMutation {
	return _c.mutation
}

// Save creates the SystemConfig in the database.
func (_c *SystemConfigCreate) Save(ctx context.Context) (*SystemConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemConfigCreate) SaveX(ctx context.Context) *SystemConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := systemconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := systemconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := systemconfig.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := systemconfig.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := systemconfig.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := systemconfig.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SystemConfig.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := systemconfig.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SystemConfig.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SystemConfig.value"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "SystemConfig.category"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SystemConfig.description"`)}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "SystemConfig.is_public"`)}
	}
	return nil
}

func (_c *SystemConfigCreate) sqlSave(ctx context.Context) (*SystemConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemConfigCreate) createSpec() (*SystemConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemconfig.Table, sqlgraph.NewFieldSpec(systemconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(systemconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(systemconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(systemconfig.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(systemconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(systemconfig.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	return _node, _spec
}

// SystemConfigCreateBulk is the builder for creating many SystemConfig entities in bulk.
type SystemConfigCreateBulk struct {
	config
	err      error
	builders []*SystemConfigCreate
}

// Save creates the SystemConfig entities in the database.
func (_c *SystemConfigCreateBulk) Save(ctx context.Context) ([]*SystemConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemConfigCreateBulk) SaveX(ctx context.Context) []*SystemConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
